### ISSUE TITLE
How to install with dein

### ISSUE THREAD

**Issue by ryanmorillo** [ipod825/igit.nvim#1]
Thought I had figured out how to install in dien:

`call dein#add('nvim-lua/plenary.nvim')`
`call dein#add('ipod825/libp.nvim')`
`call dein#add('ipod825/igit.nvim', {'do': 'lua require("igit").setup()'})
`

instead every time I launch neovim I have to run:
`:lua require("igit").setup()`

**Comment by ipod825** [comment]
In you .vimrc
```
lua << EOF
require("igit").setup()
EOF
```
That should be how you do lua programming in vimscript.
