### ISSUE TITLE
Staging Current Buffer

### ISSUE THREAD

**Issue by tempegarit** [ipod825/igit.nvim#4]
I currently stage a file by running `IGit add ./mydir/file.lua`. Is there any way we can stage the current buffer?

**Comment by ipod825** [comment]
If you are looking for cmdline mode solution, you can do 
`:exec 'IGit add '..expand('%:p')`.

Otherwise, `IGit status` gives you a page for staging changed files. The default `dd` mapping even allow you to do partial staging.
